version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8081
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"  # Внешний порт 80 пробрасывается на Nginx
    depends_on:
      - flask_app
    restart: always
